language: emacs-lisp
# os:
#  - linux
#  - osx
env:
 - EMACS=emacs24
 - EMACS=emacs-snapshot
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo add-apt-repository -y ppa:cassou/emacs # emacs23, emacs24
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS
script:
  ./setup.sh install-travis