OBlanguage: emacs-lisp
env:
 - EMACS=emacs22
 - EMACS=emacs23
 - EMACS=emacs24
 - EMACS=emacs-snapshot
matrix:
  allow_failures:
    - env: EMACS=emacs22
    - env: EMACS=emacs23
before_install:
  # install emacs
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo add-apt-repository -y ppa:cassou/emacs # emacs23, emacs24
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS
  - sudo apt-get install -qq python
  - sudo apt-get install -qq python-pip
script:
  ./setup.sh install-travis